name: Build .NET

on:
  push:
    branches: [ develop ]
    paths:
    - 'src/**'
    - 'tests/**'
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: ['2.1.x']

    name: Build and Test against Dotnet ${{ matrix.dotnet }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
